### ISSUE TITLE
Unable to build the application in windows using visual 2019

### ISSUE THREAD

**Issue by rsrini83** [syncfusion/Xamarin-ExpenseAnalysis#20]
Unable to deploy to android or simulator with the latest code. Getting below exception

![image](https://user-images.githubusercontent.com/16274962/78916938-d3d26a00-7aab-11ea-823c-fb6c6cd952ad.png)

Severity	Code	Description	Project	File	Line	Suppression State
Error		XARDF7023: System.IO.DirectoryNotFoundException: Could not find a part of the path 'AlertDialog_IDialogInterfaceOnMultiChoiceClickListenerImplementor.class'.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Xamarin.Android.Tasks.RemoveDirFixed.RunTask()		 	0	
Error		XARDF7004: System.ArgumentException: Illegal characters in path.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Xamarin.Android.Tasks.RemoveDirFixed.RunTask()		 	0

**Comment by RathanakumarSekar** [comment]
Hi @rsrini83 

Thank you for contacting us.

We have tried to reproduce the reported issue "Unable to build the application in windows using visual 2019" and we were unable to reproduce the reported issue. We could deploy and run the sample without any issues. Can you clean and rebuild the project once again?

Please let us know if the issue still exists from your end even after rebuilding the application.

Thanks,
Rathanakumar S

**Comment by rsrini83** [comment]
Hi @RathanakumarSekar ,

Thanks for your reply. Yes, i had done multiple times cleaning the solution and trying to deploy. However, i'm always hitting the same error.

My environment is,
Visual Studio: 2019
Xamarin.Forms; 3.6.0.344457 (did not modify anything, same as in the Gitcode).
Android: Default emulator, Nexus 10 Pie 9.0 - API 28

**Comment by RathanakumarSekar** [comment]
Hi rsrini83, 
 
Thanks for your update. 
 
We have checked the reported issue "Unable to build the application " in Visual Studio 2019 Windows 16.3.8 and Mac 8.5 versions. Still, we were unable to reproduce the reported issue. So, could you please provide the version details about your Visual Studio IDE. 
It will help us to provide an appropriate solution on this. 
 
Please let us know if you need any further assistance.      
  
Thanks, 
Rathanakumar S

**Comment by Prabhuss** [comment]
Hi Rathankumar,

Here are the details you asked,

![image](https://user-images.githubusercontent.com/26796392/79948797-25a6c700-8492-11ea-8339-a47772518ea3.png)

Let me know if you need any further information. 

--Srinu

**Comment by mrhemalatha** [comment]
Hi @Prabhuss 

We have ensured the same with the provided configured VS  but that is working fine at our end. Any further details to replicate the issue then please share to us. Please clear the cache and bin,obj and close the application and reopen it

**Comment by jmbigi** [comment]
Hi @rsrini83,

Try moving your project to a simpler path like c:\Proj01, this problem could be because of the project path as you got this error:
Error XARDF7004: System.ArgumentException: Invalid characters in path.
I got here because I got similar error messages, shortened my project path, removed spaces in the folder name and worked.
I hope this works for you. Thanks for sharing
